#pragma once

#include <projectversion.h>

#define AUDIOPLUGIN_PLUGIN_VERSION_STR VERSION_STR

#define AUDIOPLUGIN_PLUGIN_VERSION_MAJOR_STR MAJOR_VERSION_STR

#define AUDIOPLUGIN_PLUGIN_VERSION_MAJOR_INT MAJOR_VERSION_INT

#define AUDIOPLUGIN_PLUGIN_VERSION_SUB_STR SUB_VERSION_STR

#define AUDIOPLUGIN_PLUGIN_VERSION_SUB_INT SUB_VERSION_INT

#define AUDIOPLUGIN_PLUGIN_VERSION_RELEASE_STR RELEASE_NUMBER_STR

#define AUDIOPLUGIN_PLUGIN_VERSION_RELEASE_INT RELEASE_NUMBER_INT

#define AUDIOPLUGIN_PLUGIN_VERSION_BUILD_STR BUILD_NUMBER_STR

#define AUDIOPLUGIN_PLUGIN_VERSION_BUILD_INT BUILD_NUMBER_INT

#define AUDIOPLUGIN_PLUGIN_FILENAME AUDIOPLUGIN_PLUGIN_NAME ".vst3"

#define AUDIOPLUGIN_PLUGIN_FILEDESC AUDIOPLUGIN_PLUGIN_NAME

#define AUDIOPLUGIN_PLUGIN_COPYRIGHT "Copyright(c) 2023 " AUDIOPLUGIN_PLUGIN_COMPANY

#define AUDIOPLUGIN_PLUGIN_LEGAL "VST is a trademark of Steinberg Media Technologies GmbH"
