#pragma once

#include <pluginterfaces/base/fplatform.h>

#include <projectversion.h>

#define PLUGIN_VERSION VERSION_STR
#define PLUGIN_VERSION_FULL FULL_VERSION_STR
#define PLUGIN_VERSION_MAJOR_STR MAJOR_VERSION_STR
#define PLUGIN_VERSION_MAJOR_INT MAJOR_VERSION_INT
#define PLUGIN_VERSION_SUB_STR SUB_VERSION_STR
#define PLUGIN_VERSION_SUB_INT SUB_VERSION_INT
#define PLUGIN_VERSION_RELEASE_STR RELEASE_NUMBER_STR
#define PLUGIN_VERSION_RELEASE_INT RELEASE_NUMBER_INT
#define PLUGIN_VERSION_BUILD_STR BUILD_NUMBER_STR
#define PLUGIN_VERSION_BUILD_INT BUILD_NUMBER_INT

#define PLUGIN_NAME LIBPLUGIN_PLUGIN_NAME
#define PLUGIN_COMPANY LIBPLUGIN_PLUGIN_COMPANY
#define PLUGIN_TYPE LIBPLUGIN_PLUGIN_TYPE
#define PLUGIN_DESCRIPTION LIBPLUGIN_PLUGIN_DESCRIPTION

#define PLUGIN_FILENAME LIBPLUGIN_PLUGIN_NAME ".vst3"
#define PLUGIN_FILEDESC LIBPLUGIN_PLUGIN_NAME
#define PLUGIN_COPYRIGHT "Copyright(c) 2023 " PLUGIN_COMPANY
#define PLUGIN_LEGAL "VST is a trademark of Steinberg Media Technologies GmbH"
