name: Linux CI

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        backend: ["VST3"]    
        
    name: ${{ matrix.backend }} (${{ matrix.build_type }})

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -DLIBAUDIOPLUGIN_BUILD_EXAMPLE:BOOL=ON -DLIBAUDIOPLUGIN_PREFERRED_BACKEND:STRING=${{ matrix.backend }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target ExamplePlugin --config ${{ matrix.build_type }}
