name: MacOS CI

on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Debug", "Release"]
        backend: ["AAX", "AU2", "AU3", "VST2", "VST3"]

    name: ${{ matrix.backend }} (${{ matrix.build_type }})

    steps:
      - uses: actions/checkout@v3
      
      - name: Configure
        run: cmake -B ${{ github.workspace }}/build -DLIBAUDIOPLUGIN_BUILD_EXAMPLE:BOOL=ON -DLIBAUDIOPLUGIN_BUILD_BACKEND:STRING=${{ matrix.backend }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --target ExamplePlugin --config ${{ matrix.build_type }}

